export const monthlyOperationalNarrative = {
  siteLabel: 'All Sites',
  generatedByLabel: 'Generated by SAGE',
  downloadLabel: 'Download PDF',
  downloadingLabel: 'Downloading...',
  downloadedLabel: 'Downloaded',
  shareLabel: 'Share',
  sectionTitles: {
    executiveSummary: 'Executive Summary',
    sitePerformance: 'Site Performance',
    patterns: 'Patterns Across Regions',
    actions: 'Recommended Actions',
  },
  months: {
    march: {
      label: 'March 2026',
      title: 'SAGE Monthly Briefing - March 2026',
      timestamp: 'Generated Mar 31, 2026 at 6:00 AM',
      summary:
        'Overall operations improved modestly in March, with the regional SAGE score rising from 79 to 82. Inspection coverage reached 87% across all sites, up 4 points from February. Work item backlog decreased by 18%, though ASU Downtown remains a concern with persistent overdue items. One recordable safety incident was reported and is under review.',
      sites: [
        {
          name: 'Estrella Community College',
          score: '88',
          delta: '+3',
          direction: 'up',
          bullets: [
            'Inspection scores improved 6% driven by consistent daily lobby coverage',
            'All work items resolved within SLA for the first time in Q1',
            'One near-miss reported and addressed same-day',
          ],
        },
        {
          name: 'ASU Downtown',
          score: '72',
          delta: '-5',
          direction: 'down',
          bullets: [
            'Joint inspection frequency fell below monthly target (62% vs 80% goal)',
            '4 work items overdue in Building B, oldest at 12 days',
            'Safety incident (slip/fall) still pending root cause investigation',
          ],
        },
        {
          name: 'Palm Springs Medical',
          score: '81',
          delta: '+1',
          direction: 'up',
          bullets: [
            'Resolved 3-month grout backlog in east wing restrooms',
            'Customer satisfaction survey score rose to 4.2/5',
            'Staffing gap on weekends affecting evening shift coverage',
          ],
        },
      ],
      patterns: [
        'Work item aging correlates strongly with sites that have below-target joint inspection rates',
        'Sites with daily supervisor touchpoints consistently score 10+ points higher',
        'Weekend staffing gaps are emerging as a regional trend - 2 of 3 sites affected',
      ],
      actions: [
        'Escalate ASU Downtown overdue work items to regional manager',
        'Schedule joint inspection catch-up sessions at ASU by April 10',
        'Develop weekend staffing plan for Palm Springs and ASU',
        'Close open safety incident investigation within 48 hours',
      ],
    },
    february: {
      label: 'February 2026',
      title: 'SAGE Monthly Briefing - February 2026',
      timestamp: 'Generated Feb 28, 2026 at 6:00 AM',
      summary:
        'February saw mixed results across the portfolio. The regional SAGE score held steady at 79, with inspection coverage at 83%. Work item backlog grew by 9%, primarily driven by deferred maintenance at ASU Downtown and weekend staffing constraints at Palm Springs Medical. No recordable safety incidents were reported this month.',
      sites: [
        {
          name: 'Estrella Community College',
          score: '85',
          delta: '+2',
          direction: 'up',
          bullets: [
            'Consistent lobby inspection routine maintained throughout the month',
            'Two overdue work items from January closed within first week',
            'Night shift coverage improved after schedule adjustment',
          ],
        },
        {
          name: 'ASU Downtown',
          score: '77',
          delta: '-2',
          direction: 'down',
          bullets: [
            'Joint inspection rate at 71%, below the 80% monthly target',
            'Building B restroom grout issues deferred for third consecutive month',
            'Supervisor vacancy filled mid-month; onboarding in progress',
          ],
        },
        {
          name: 'Palm Springs Medical',
          score: '80',
          delta: '0',
          direction: 'up',
          bullets: [
            'Customer satisfaction steady at 3.9/5',
            'East wing restroom grout backlog persists; vendor quote received',
            'Weekend evening shift running at 60% staffing two weekends in a row',
          ],
        },
      ],
      patterns: [
        'Sites with supervisor vacancies show a 5-8 point SAGE score decline within 30 days',
        'Deferred maintenance items older than 30 days correlate with lower customer satisfaction',
        'Joint inspection adherence is the strongest leading indicator of monthly score movement',
      ],
      actions: [
        'Prioritize grout repair vendor approval for ASU Downtown and Palm Springs',
        'Complete onboarding for new ASU Downtown supervisor by March 7',
        'Review weekend staffing model across all three sites',
        'Set joint inspection recovery targets for March',
      ],
    },
  },
} as const;
