import { fireEvent, render } from '@testing-library/react-native';

import { MonthlyOperationalNarrativeScreen } from '@/src/features/prototypes/screens/MonthlyOperationalNarrativeScreen';

jest.mock('expo-router', () => ({
  Link: ({ children, href }: { children: any; href: string }) => {
    const { View } = require('react-native');
    return <View testID={`link:${href}`}>{children}</View>;
  },
}));

jest.mock('@/src/hooks/useLocalizedText', () => ({
  useLocalizedText: (value: string) => value,
}));

describe('MonthlyOperationalNarrativeScreen', () => {
  it('renders the monthly briefing body for march by default', () => {
    const { getByRole, getByText } = render(<MonthlyOperationalNarrativeScreen />);

    expect(getByText('All Sites')).toBeTruthy();
    expect(getByText('March 2026')).toBeTruthy();
    expect(getByText(/Generated by SAGE/)).toBeTruthy();
    expect(getByText('SAGE Monthly Briefing - March 2026')).toBeTruthy();
    expect(getByText('Generated Mar 31, 2026 at 6:00 AM')).toBeTruthy();
    expect(getByText('Executive Summary')).toBeTruthy();
    expect(
      getByText(
        'Overall operations improved modestly in March, with the regional SAGE score rising from 79 to 82. Inspection coverage reached 87% across all sites, up 4 points from February. Work item backlog decreased by 18%, though ASU Downtown remains a concern with persistent overdue items. One recordable safety incident was reported and is under review.',
      ),
    ).toBeTruthy();
    expect(getByText('Site Performance')).toBeTruthy();
    expect(getByText('Estrella Community College')).toBeTruthy();
    expect(getByText('ASU Downtown')).toBeTruthy();
    expect(getByText('Palm Springs Medical')).toBeTruthy();
    expect(getByText('Patterns Across Regions')).toBeTruthy();
    expect(getByText('Recommended Actions')).toBeTruthy();
    expect(getByRole('button', { name: 'Download PDF' })).toBeTruthy();
    expect(getByRole('button', { name: 'Share' })).toBeTruthy();
  });

  it('switches between february and march using the month controls', () => {
    const { getByRole, getByText, queryByText } = render(<MonthlyOperationalNarrativeScreen />);

    fireEvent.press(getByRole('button', { name: 'Previous month' }));

    expect(getByText('February 2026')).toBeTruthy();
    expect(getByText('SAGE Monthly Briefing - February 2026')).toBeTruthy();
    expect(
      getByText(
        'February saw mixed results across the portfolio. The regional SAGE score held steady at 79, with inspection coverage at 83%. Work item backlog grew by 9%, primarily driven by deferred maintenance at ASU Downtown and weekend staffing constraints at Palm Springs Medical. No recordable safety incidents were reported this month.',
      ),
    ).toBeTruthy();
    expect(queryByText('SAGE Monthly Briefing - March 2026')).toBeNull();

    fireEvent.press(getByRole('button', { name: 'Next month' }));
    expect(getByText('SAGE Monthly Briefing - March 2026')).toBeTruthy();
  });

  it('supports downloading the briefing locally', () => {
    const { getByRole, getByText } = render(<MonthlyOperationalNarrativeScreen />);

    fireEvent.press(getByRole('button', { name: 'Download PDF' }));

    expect(getByText(/Downloaded/)).toBeTruthy();
  });
});
